### ISSUE TITLE
Cannot build a working CSharp plugin from the example

### ISSUE THREAD

**Issue by falldeaf** [Flow-Launcher/plugin-samples#4]
I've downloaded and built the HelloWorldCSharp example exactly as-is in Visual Studio 2022. It builds successfully and creates what looks like the correct files in the /bin directory. I renamed the 'debug' folder to 'Hello World CSharp-1.0.0' and moved it into 'C:\Users\\[myusername]\AppData\Roaming\FlowLauncher\Plugins\'.

When I restart flow launcher I get a pop-up saying to look at the logs and when I open the logs I'm getting the following error:
```log
17:59:16.7073-04:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
17:59:16.7073-04:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True
17:59:16.8195-04:00 - INFO  - ImageLoader.Initialize - Preload images cost <34ms>
17:59:16.8195-04:00 - INFO  - ImageLoader.Initialize - Number of preload images is <2>, Images Number: 2, Unique Items 2
17:59:17.1403-04:00 - ERROR - PluginsLoader.DotNetPlugins - Can't find the required IPlugin interface for the plugin: <Hello World CSharp>
EXCEPTION OCCURS: System.InvalidOperationException: Sequence contains no matching element
   at void System.Linq.ThrowHelper.ThrowNoMatchException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
   at Type Flow.Launcher.Core.Plugin.PluginAssemblyLoader.FromAssemblyGetTypeOfInterface(Assembly assembly, Type type) in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs:line 44
   at IEnumerable<PluginPair> Flow.Launcher.Core.Plugin.PluginsLoader.DotNetPlugins(List<PluginMetadata> source)+() => { } in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/PluginsLoader.cs:line 58
```

The Main.cs looks like the following (unchanged from this code in this repo)
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Flow.Launcher.Plugin;

namespace HelloWorldCSharp
{
    class Main : IPlugin
    {
        public List<Result> Query(Query query)
        {
            var result = new Result
            {
                Title = "Hello World from CSharp",
                SubTitle = $"Query: {query.Search}",
                IcoPath = "app.png"
            };
            return new List<Result> {result};
        }

        public void Init(PluginInitContext context)
        {
            
        }
    }
}
```

**Comment by jjw24** [comment]
@taooceros, the main project in dev is expecting type IAsyncPlugin when loading dotnet plugins, is this the type to be used going forward?

**Comment by taooceros** [comment]
> @taooceros, the main project in dev is expecting type IAsyncPlugin when loading dotnet plugins, is this the type to be used going forward?

Hm is it possible that the hello world plug-in reference a very old plugin lib?
Iplugin should extend from iasyncplugin with a default implementation.

**Comment by jjw24** [comment]
> > @taooceros, the main project in dev is expecting type IAsyncPlugin when loading dotnet plugins, is this the type to be used going forward?
> 
> Hm is it possible that the hello world plug-in reference a very old plugin lib? Iplugin should extend from iasyncplugin with a default implementation.

Nop 🤦 , using the latest Plugin library, but turns out it was the main class' visibility which [was not set to public](https://github.com/Flow-Launcher/plugin-samples/commit/9079fd24ec82fc91ca2ae5b97e25ab480b6fc26c#diff-35d83e96c9dd37ec20e5f796aa83fc54ec74e29e81f8236b701755b50e6602d9R6) that caused the plugin loading to fail because the loader was not able to find the project assembly's ExportedTypes. 

Misleading exception coming from the PluginAssemblyLoader, took me a while to actually realise it was a class visibility issue.

**Comment by jjw24** [comment]
@falldeaf  thank you for reporting this. This error is fixed and if you download the plugin now should work. I have also added language translation support example in the code to show how different languages can be implemented.
